eoh_rl:
  task_family: tsp
  local_model_path: /home/yuanyilun/models/deepseek-coder-7b-instruct-v1.5
  inference_gpus: [2]
  inference_ports: [22003]
  training_gpus: [2]
  pytorch_alloc_conf: "expandable_segments:True"
  sft:
    mode: load_existing
    output_dir: /home/yuanyilun/projects/source/LLM4AD/data/SFT/tsp/small
    load_lora_path: /home/yuanyilun/projects/LLM4AD/data/SFT/tsp/small/lora_sft
    source_dirs: [/home/yuanyilun/projects/LLM4AD/data/tsp_eoh]
  logging:
    log_base_dir: /home/yuanyilun/projects/source/LLM4AD/logs
  tsp:
    task_name: tsp_construct
    default_scale: small
    scales:
      small:
        problem_size: 50
        n_instance: 64
        timeout_seconds: 120
        pop_size: 10
      medium-100:
        problem_size: 100
        n_instance: 64
        timeout_seconds: 120
        pop_size: 10
      medium-200:
        problem_size: 200
        n_instance: 64
        timeout_seconds: 120
        pop_size: 10
